sonar.organization=hellorin
sonar.projectKey=Timeforge
sonar.projectName=Timeforge

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.jsx,**/*.test.js

sonar.sourceEncoding=UTF-8
